-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."coin"
(
    "id" bigserial NOT NULL,
    "portfolio_id" bigserial NOT NULL,
    coin_name character varying(32) NOT NULL,
    coin_code character varying(4) NOT NULL,
    price double precision NOT NULL,
    volume double precision NOT NULL,
    last_price integer[],
    CONSTRAINT "coin_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."coin_market_info"
(
    coin_name character varying(32) COLLATE pg_catalog."default" NOT NULL,
    coin_code character varying(4) COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    "1h" double precision NOT NULL,
    "24h" double precision NOT NULL,
    "7d" double precision NOT NULL,
    market_cap double precision NOT NULL,
    volume double precision NOT NULL,
    last_price integer[] NOT NULL,
    id bigserial NOT NULL,
    CONSTRAINT "coin_market_info_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Trend"
(
    coin_name character varying(32) NOT NULL,
    coin_code character varying(4) NOT NULL,
    "24h" double precision NOT NULL,
    PRIMARY KEY (coin_name, coin_code)
);

CREATE TABLE IF NOT EXISTS public."exchange"
(
    exchange_name character varying(20) NOT NULL,
    score double precision NOT NULL,
    volume24h bigint NOT NULL DEFAULT 0,
    markets bigint NOT NULL,
    coins bigint NOT NULL,
    last_volume integer[] NOT NULL,
    CONSTRAINT "exchange_pkey" PRIMARY KEY (exchange_name)
);

CREATE TABLE IF NOT EXISTS public."deal"
(
    "id" bigserial NOT NULL,
    "portfolio_id" bigserial NOT NULL,
    date date NOT NULL,
    type character varying(4) NOT NULL,
    price double precision NOT NULL,
    volume double precision NOT NULL,
    coin_name character varying(32) NOT NULL,
    coin_code character varying(4) NOT NULL,
    CONSTRAINT "deal_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."portfolio"
(
    "id" bigserial NOT NULL,
    profile_volume_usd double precision[],
    profile_volume_btc double precision[],
    current_volume_usd double precision,
    current_volume_btc double precision,
    PRIMARY KEY ("id")
);

ALTER TABLE IF EXISTS public."coin"
    ADD CONSTRAINT "coin_fkey" FOREIGN KEY ("portfolio_id")
    REFERENCES public."Portfolio" ("id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."deal"
    ADD CONSTRAINT "deal_fkey" FOREIGN KEY ("portfolio_id")
    REFERENCES public."portfolio" ("id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;